name: Shop Application API Testing

on: 
  push:
  workflow_dispatch:

jobs:
  run-shop-api-tests:
    name: Execute Shop App API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Newman and Reporters
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-allure

      - name: Create Directory for Test Results
        run: mkdir -p testResults

      - name: Execute Postman Collection
        run: |
          newman run Shop_final.json -e Shop_environment.json -r htmlextra,cli,allure --reporter-htmlextra-export testResults/htmlreport.html --reporter-allure-export testResults/allure-results > testResults/output.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: testResults

      - name: Checkout Test History
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: testResults/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
