name: Test-Postman
on: [push, workflow_dispatch]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      # Install Node.js on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"


      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run:
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-allure


      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults


      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run:
          newman run Shop_final.json -e Shop_environment.json -r htmlextra,cli,allure --reporter-htmlextra-export testResults/htmlreport.html --reporter-allure-export testResults/allure-results > testResults/output.txt

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
      
      # Download tests history
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          
      # Generate Allure report
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: testResults/allure-results
          allure_report: allure-report
          allure_history: allure-history
          
      # Publish report
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
